#include "source_queue.h"

DECLARE_FUNC_IS_VALID(AudioSource)
DECLARE_FUNC_COPY(AudioSource)
DECLARE_FUNC_GET_END_TIME_MS(AudioSource)
DECLARE_FUNC_BUBBLE_SORT(AudioSource)
DECLARE_FUNC_SIZE(AudioSource)
DECLARE_FUNC_FLUSH(AudioSource)
DECLARE_FUNC_FREE(AudioSource)
DECLARE_FUNC_FREEP(AudioSource)
DECLARE_FUNC_GET(AudioSource)
DECLARE_FUNC_PUT(AudioSource)
DECLARE_FUNC_CREATE(AudioSource)

